### ISSUE TITLE
agent and runtime cannot pass travis-ci after switch to golangci-lint

### ISSUE THREAD

**Issue by teawater** [kata-containers/tests#1345]
After merge https://github.com/kata-containers/tests/pull/1315
travis-ci failed in:
https://github.com/kata-containers/runtime/pull/1409
https://github.com/kata-containers/runtime/pull/1410
https://github.com/kata-containers/agent/pull/493
```
=== CONT  TestSourcesFromTestdataWithIssuesDir/depguard.go
--- FAIL: TestSourcesFromTestdataWithIssuesDir (0.30s)
	linters_test.go:38: testdata/*.go
    --- FAIL: TestSourcesFromTestdataWithIssuesDir/ineffassign.go (0.26s)
    	linters_test.go:137: [run --disable-all --print-issued-lines=false --print-linter-name=false --out-format=line-number -Eineffassign --no-config testdata/ineffassign.go]
    	require.go:794: 
    			Error Trace:	linters_test.go:34
    			            				linters_test.go:138
    			            				linters_test.go:54
    			Error:      	Received unexpected error:
    			            	
    			            	unmatched errors
    			            	2019/03/23 00:41:15 unknown architecture wasm
    			Test:       	TestSourcesFromTestdataWithIssuesDir/ineffassign.go
    --- FAIL: TestSourcesFromTestdataWithIssuesDir/deadcode.go (0.26s)
...
...
```

**Comment by teawater** [comment]
Just reproduced the issue in my part.
Upstream golangci-lint cannot pass test with go1.10.8.  But OK with go1.12.1.

**Comment by teawater** [comment]
```
  golangci-lint:
    description: "utility to run various golang linters"
    url: "github.com/golangci/golangci-lint"
    # Using HEAD for now as v1.15.0 does not compile with golang 1.12+. Will be
    # pegged to the next release once it comes out.
    # https://github.com/kata-containers/tests/issues/1329
    version: "HEAD"
```
golangci-lint v1.15.0 cannot work with golang 1.12+
golangci-lint HEAD cannot work with go1.10.8
