### ISSUE TITLE
Add shimv2 testing for crio

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#1624]
Today we have CI for containerd shimv2. We need to do the same for crio as a first step.
Following that tests need to be added to upstream crio to check kata with shimv2.
Today we run tests in crio repo for testing just shim v1.
cc @chavafg

**Comment by chavafg** [comment]
@amshinde @sboeuf 
Do you know how can I configure `shimv2` for `cri-o`? 

For `containerd` I see that there is a `containerd-shim-kata-v2`, but for cri-o I dont see something similar.

**Comment by sboeuf** [comment]
Hi @chavafg,
Both `CRI-O` and `containerd` rely on `containerd-shim-kata-v2` binary.
You need to provide this binary through the `crio.conf` file. Something along those lines:
```toml
  # The "crio.runtime.runtimes" table defines a list of OCI compatible runtimes.
  # The runtime to use is picked based on the runtime_handler provided by the CRI.
  # If no runtime_handler is provided, the runtime will be picked based on the level
  # of trust of the workload.
  
  [crio.runtime.runtimes.runc]
  runtime_path = "/usr/bin/runc"

  [crio.runtime.runtimes.kata]
  #runtime_path = "/usr/bin/kata-runtime"
  runtime_path = "/usr/bin/containerd-shim-kata-v2"
  runtime_type = "vm"
```
