### ISSUE TITLE
k8s: use Wave Net on AArch64 instead of flannel

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/tests#1742]
# Description of problem
flannel pod always got OOM killed on AArch64.
flannel pod has set memory limitation:
```
containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.10.0-arm64
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
```
oom-killer logs in dmesg:
```
kernel: [429178.253663] conmon invoked oom-killer: gfp_mask=0x6000c0(GFP_KERNEL), order=0, oom_score_adj=-999
700]  oom_kill_process+0x330/0x370
kernel: [429178.253701]  out_of_memory+0x1b4/0x510
kernel: [429178.253708]  mem_cgroup_out_of_memory+0xc4/0xe0
kernel: [429178.253736] memory: uIsage 51200kB, limit 51200kB, failcnt 100154
kernel: [429178.264979] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=crio-conmon-095c9da0df6d2e4d867f3f757ae46adaa44860597e670f18ebb0268c91d04c65,mems_allowed=0-1,oom_memcg=/kubepods/podb70c2d7b-9241-11e9-a761-6805ca836f34,task_memcg=/kubepods/podb70c2d7b-9241-11e9-a761-6805ca836f34/crio-conmon-095c9da0df6d2e4d867f3f757ae46adaa44860597e670f18ebb0268c91d04c65,task=conmon,pid=158604,uid=0
kernel: [429178.264988] Memory cgroup out of memory: Kill process 158604 (conmon) score 0 or sacrifice child
```
This error look like arch-irrelevant, I have found similar issue [coreos/flannel/#963](https://github.com/coreos/flannel/issues/963
) here on x86-64.
So I decided to switch to use Wave Net. ;)
