### ISSUE TITLE
ci: clh ci is broken for images reporting wrong disk alignment

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/tests#2601]
# Description of problem
We have seen some jobs that started to report 500 error from cloud-hypervisor
```
Jun 03 19:40:09 ubuntu1804-azure1f9ef0 kata-runtime[30282]: time="2020-06-03T19:40:09.053066332Z" level=error msg="error: 500  reason: VmBoot(VmBoot(DeviceManager(PmemSizeNotAligned)))" arch=amd64 command=create container=596281bf95b7377528b405c77d1d5c37aee06de5d56cde3294b66fa192075554 name=kata-runtime pid=30282 source=runtime
Jun 03 19:40:08 ubunt
```
Seems that the disk size is not aligned for hotplug, looking at osbuider I dont see any change that could lead to change the image size.

**Comment by jcvenegas** [comment]
Looking for recent changes in http://jenkins.katacontainers.io/job/image-nightly-x86_64 
 This is the lest build, I will remove the cached jobs to confirm it is not an issue with the image what is cached we will go to Clear 33260 as last cached image
```
---
osbuilder:
  url: "https://github.com/kata-containers/osbuilder"
  version: "unknown"
rootfs-creation-time: "2020-06-02T19:19:56.465296792+0000Z"
description: "osbuilder rootfs"
file-format-version: "0.0.2"
architecture: "x86_64"
base-distro:
  name: "Clear"
  version: "33270"
  packages:
    default:
      - "chrony"
      - "iptables-bin"
      - "kmod-bin"
      - "libudev0-shim"
      - "systemd"
      - "util-linux-bin"
    extra:

agent:
  url: "https://github.com/kata-containers/agent"
  name: "kata-agent"
  version: "1.11.0-rc0-906f7e2e4c52c568f0d990b3c049f863546df848"
  agent-is-init-daemon: "no"

```
Also we dont report the size in the toml I would be nice for future references.
