### ISSUE TITLE
Add test to verify init containers work

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#2825]
Till the latest Kata release, init containers were broken with cloud hypervisor in k8s. We should have had a test in place that verifies this. Lets add this to our existing pod test yamls for qemu and clh.
Could be as simple as just running `date` to test init containers exit cleanly. Note, useful to test this with devicemapper to make sure block devices are unplugged correctly.
```
apiVersion: v1
kind: Pod
metadata:
  name: threecontainers
spec:
  runtimeClassName: kata-clh
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['date']
```

cc @GabyCT @jcvenegas @likebreath
