### ISSUE TITLE
Add test to verify more than 10 containers can be launched in a pod with shimv2 api.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/tests#2826]
This is to verify https://github.com/kata-containers/runtime/issues/2795. 
We need to test qemu and clh as well once this fix is added to clh.

Workload to test:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qemu-guest-empty-dir
spec:
  selector:
    matchLabels:
      app: qemu-guest-empty-dir
  replicas: 1
  template:
    metadata:
      labels:
        app: qemu-guest-empty-dir
      annotations:
              #io.katacontainers.config.hypervisor.memory_slots: "15"
        #io.katacontainers.config.hypervisor.image: "/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.9.1_agent_d4bbd8007f.img"
    spec:
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/kata-containers
          operator: Equal
          value: "true"
      containers:
        - image: dmonakhov/alpine-fio
          name: qemu-0
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-1
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-2
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-3
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-4
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-5
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-6
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-7
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-8
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-9
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
        - image: dmonakhov/alpine-fio
          name: qemu-10
          command: ["ash"]
          stdin: true
          volumeMounts:
            - name: test-volume
              mountPath: /test-volume
          tty: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "150m"
      restartPolicy: Always
      runtimeClassName: kata-clh
      volumes:
        - name: test-volume
          emptyDir: {}
```
