### ISSUE TITLE
kubernetes: add test to check CPU constrains

### ISSUE THREAD

**Issue by devimc** [kata-containers/tests#309]
Next yaml can be used as base for this test, but it needs to be improved to check the constrains

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: sandbox
spec:
  containers:
  - name: cpu0
    image: debian
    resources:
      limits:
        cpu: "1"
    args:
    - "bash"
    tty: true
    stdin: true
  - name: cpu1
    image: debian
    resources:
      limits:
        cpu: "3"
    args:
    - "bash"
    - "-c"
    - "sleep 5; nproc"
    tty: true
    stdin: true
```
