### ISSUE TITLE
Building Rust components with *newest* supported Rust version in the CI is unhelpful

### ISSUE THREAD

**Issue by dgibson** [kata-containers/tests#4188]
# Description of problem

The `versions.yaml` in the main Kata repository has both oldest and newest supported versions for the Rust compiler:

```
  rust:
    description: "Rust language"
    notes: "'version' is the default minimum version used by this project."
    version: "1.45.0"
    meta:
      description: |
        'newest-version' is the latest version known to work when
        building Kata
      newest-version: "1.54.0"
```

The `.ci/install_rust.sh` script installs Rust based on the newest version listed.  AFAICT none of the scripts in either the main or tests repository examine the oldest version.  This isn't particularly useful:
- Rust has a strong commitment to backwards compatibility, any newer Rust version will generally be fine
- If there is a compatibility problem with a new Rust version, that's a bug in Rust - which means that it doesn't tell us anything about later or intervening versions, so "newest tested" doesn't really tell us anything except that that *specific* version has been tested.
- On the other hand, accidentally introducing things into the Kata codebase which require newer Rust features that the oldest one listed is absolutely posslble, and might not get caught by the CI (it may get caught by some of the extra cases which don't use `install_rust.sh`, but it's not tested systematically)

# Expected result

CI should build with the *oldest* supported Rust version, to ensure that all Kata code works with the features in the oldest supported Rust.

# Actual result

CI runs with the "newest known to work" Rust version.
